### ISSUE TITLE
Bug in on-device curand reproducibility (was: differences for GPU execution bridge / no bridge)

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#429] opened 2022-04-12 13:40 UTC
With the current branch I'm observing a strange behaviour when running (g)check.exe. 

The produced values for check.exe (CPU) with or without the bridge option and also gcheck.exe with the bridge option are the same. 

Running with gcheck.exe without bridge option I can currently produce different output results. E.g. I'm showing below the command lines and the last result

Executing
```
roiser@itscrd02:P1_Sigma_sm_gg_ttx (master)$ ./gcheck.exe -v 32 32 2
```
produces last result 
```
Momenta:
   1  7.500000e+02  0.000000e+00  0.000000e+00  7.500000e+02
   2  7.500000e+02  0.000000e+00  0.000000e+00 -7.500000e+02
   3  7.500000e+02  1.977175e+02 -5.098854e+01 -7.216702e+02
   4  7.500000e+02 -1.977175e+02  5.098854e+01  7.216702e+02
-------------------------------------------------------------------------------
 Matrix element = 10.8827 GeV^0
-------------------------------------------------------------------------------
```

while executing 

```
roiser@itscrd02:P1_Sigma_sm_gg_ttx (master)$ ./gcheck.exe -v --bridge 32 32 2
```
produces last result

```
Momenta:
   1  7.500000e+02  0.000000e+00  0.000000e+00  7.500000e+02
   2  7.500000e+02  0.000000e+00  0.000000e+00 -7.500000e+02
   3  7.500000e+02 -6.264599e+02 -4.169666e+01 -4.102552e+02
   4  7.500000e+02  6.264599e+02  4.169666e+01  4.102552e+02
-------------------------------------------------------------------------------
 Matrix element = 0.862187 GeV^0
-------------------------------------------------------------------------------
```

The binaries are produced with a plain "make" in the P1 directory. 

Also important to note is that the above difference does not show up with 1 iteration, e.g. executing

```
roiser@itscrd02:P1_Sigma_sm_gg_ttx (master)$ ./gcheck.exe -v --bridge 32 32 1
```

and

```
roiser@itscrd02:P1_Sigma_sm_gg_ttx (master)$ ./gcheck.exe -v 32 32 1
```

produces same results for me.

**Comment by valassi** [comment] 2022-04-14 08:51
Hi Stefan, thanks, I am looking into this. This is very peculiar.
```
for args in "-p 32 32 1" "-p 32 32 2" "-p 32 256 2"; do
  for brd in "" "--bridge"; do
    for exe in "./check.exe " "./gcheck.exe"; do
      cmd="$exe $brd $args"
      printf "%-36s ==> " "$cmd"
      eval $cmd | grep MeanM
    done
  done
  echo "------------------------------"
done

./check.exe   -p 32 32 1             ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
./gcheck.exe  -p 32 32 1             ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
./check.exe  --bridge -p 32 32 1     ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
./gcheck.exe --bridge -p 32 32 1     ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
------------------------------
./check.exe   -p 32 32 2             ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
./gcheck.exe  -p 32 32 2             ==> MeanMatrixElemValue         = ( 2.151629e+00 +- 8.326816e-02 )  GeV^0
./check.exe  --bridge -p 32 32 2     ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
./gcheck.exe --bridge -p 32 32 2     ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
------------------------------
./check.exe   -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe  -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./check.exe  --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
------------------------------
```

There is clearly a bug, but it's weird.
- Maybe it is there since some time? It may have escaped detection because in my logs I only test one iteration, usually.
- It clearly has to do with iterations, but that's not the whole story. It happends with 32 threads, not with 256?
- And it only happens with GPUs...

Investigating...

**Comment by valassi** [comment] 2022-04-14 08:54
By adding --common this does not happen. It must have something to do with curand's precaching, I would guess
```
./check.exe   -p 32 32 1 --common              ==> MeanMatrixElemValue         = ( 2.078496e+00 +- 1.137648e-01 )  GeV^0
./gcheck.exe  -p 32 32 1 --common              ==> MeanMatrixElemValue         = ( 2.078496e+00 +- 1.137648e-01 )  GeV^0
./check.exe  --bridge -p 32 32 1 --common      ==> MeanMatrixElemValue         = ( 2.078496e+00 +- 1.137648e-01 )  GeV^0
./gcheck.exe --bridge -p 32 32 1 --common      ==> MeanMatrixElemValue         = ( 2.078496e+00 +- 1.137648e-01 )  GeV^0
------------------------------
./check.exe   -p 32 32 2 --common              ==> MeanMatrixElemValue         = ( 2.051192e+00 +- 7.836289e-02 )  GeV^0
./gcheck.exe  -p 32 32 2 --common              ==> MeanMatrixElemValue         = ( 2.051192e+00 +- 7.836289e-02 )  GeV^0
./check.exe  --bridge -p 32 32 2 --common      ==> MeanMatrixElemValue         = ( 2.051192e+00 +- 7.836289e-02 )  GeV^0
./gcheck.exe --bridge -p 32 32 2 --common      ==> MeanMatrixElemValue         = ( 2.051192e+00 +- 7.836289e-02 )  GeV^0
------------------------------
./check.exe   -p 32 256 2 --common             ==> MeanMatrixElemValue         = ( 2.109797e+00 +- 2.796694e-02 )  GeV^0
./gcheck.exe  -p 32 256 2 --common             ==> MeanMatrixElemValue         = ( 2.109797e+00 +- 2.796694e-02 )  GeV^0
./check.exe  --bridge -p 32 256 2 --common     ==> MeanMatrixElemValue         = ( 2.109797e+00 +- 2.796694e-02 )  GeV^0
./gcheck.exe --bridge -p 32 256 2 --common     ==> MeanMatrixElemValue         = ( 2.109797e+00 +- 2.796694e-02 )  GeV^0
------------------------------

```

**Comment by valassi** [comment] 2022-04-14 09:02
Very peculiar
```
./check.exe   -p 1 32 1              ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./gcheck.exe  -p 1 32 1              ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./check.exe  --bridge -p 1 32 1      ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./gcheck.exe --bridge -p 1 32 1      ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
------------------------------
./check.exe   -p 1 32 2              ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./gcheck.exe  -p 1 32 2              ==> MeanMatrixElemValue         = ( 2.184237e+00 +- 4.514383e-01 )  GeV^0
./check.exe  --bridge -p 1 32 2      ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./gcheck.exe --bridge -p 1 32 2      ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
------------------------------
./check.exe   -p 1 256 2             ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./gcheck.exe  -p 1 256 2             ==> MeanMatrixElemValue         = ( 2.277862e+00 +- 1.843204e-01 )  GeV^0
./check.exe  --bridge -p 1 256 2     ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./gcheck.exe --bridge -p 1 256 2     ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
------------------------------
./check.exe   -p 16 256 2            ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./gcheck.exe  -p 16 256 2            ==> MeanMatrixElemValue         = ( 2.114596e+00 +- 3.945969e-02 )  GeV^0
./check.exe  --bridge -p 16 256 2    ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./gcheck.exe --bridge -p 16 256 2    ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
------------------------------
./check.exe   -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe  -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./check.exe  --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
------------------------------

```

**Comment by roiser** [comment] 2022-04-14 09:03
It's also interesting that the problem goes away by increasing the threads/block, and why it only shows up by not using the bridge on GPU?

**Comment by valassi** [comment] 2022-04-14 09:04
yes indeed... maybe i should first check why it does not happen with the bridge, maybe there are two bugs
- one in precaching
- one in the fact that the bridge uses a different path and bypasses the bug above (but it should not)

**Comment by valassi** [comment] 2022-04-14 09:07
Hm no, the reason why the bridge bypasses this is ok: it's because it uses curand host. And strangely, the issue with precaching only happens with curand device
```
./check.exe   -p 1 32 1 --curhst               ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./gcheck.exe  -p 1 32 1 --curhst               ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./check.exe  --bridge -p 1 32 1 --curhst       ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./gcheck.exe --bridge -p 1 32 1 --curhst       ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
------------------------------
./check.exe   -p 1 32 2 --curhst               ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./gcheck.exe  -p 1 32 2 --curhst               ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./check.exe  --bridge -p 1 32 2 --curhst       ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./gcheck.exe --bridge -p 1 32 2 --curhst       ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
------------------------------
./check.exe   -p 1 256 2 --curhst              ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./gcheck.exe  -p 1 256 2 --curhst              ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./check.exe  --bridge -p 1 256 2 --curhst      ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./gcheck.exe --bridge -p 1 256 2 --curhst      ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
------------------------------
./check.exe   -p 16 256 2 --curhst             ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./gcheck.exe  -p 16 256 2 --curhst             ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./check.exe  --bridge -p 16 256 2 --curhst     ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./gcheck.exe --bridge -p 16 256 2 --curhst     ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
------------------------------
./check.exe   -p 32 256 2 --curhst             ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe  -p 32 256 2 --curhst             ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./check.exe  --bridge -p 32 256 2 --curhst     ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe --bridge -p 32 256 2 --curhst     ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
------------------------------

```

**Comment by valassi** [comment] 2022-04-14 09:08
(The bridge SHOULD use curand host, this is ok - you can do it differenly, but it would be an overkill. And I was under the assumption that curand host and device would give tyhe same results, which until now always seemed to be the case...)

**Comment by valassi** [comment] 2022-04-14 09:17
I suspect this has to do with 
https://github.com/madgraph5/madgraph4gpu/blob/e2c4c0a3d66b35166bcf89cf73170f05ac872cd1/epochX/cudacpp/gg_tt/SubProcesses/RandomNumberKernels.cc#L80
```
    //checkCurand( curandSetGeneratorOrdering( *&m_rnGen, CURAND_ORDERING_PSEUDO_LEGACY ) ); // CUDA 11
    checkCurand( curandSetGeneratorOrdering( *&m_rnGen, CURAND_ORDERING_PSEUDO_BEST ) );
```
This is described in https://docs.nvidia.com/cuda/curand/host-api-overview.html#order
We are using MTGP32 for our tests

I tried to switch on CURAND_ORDERING_PSEUDO_LEGACY, which in principle should use 64 sequences instead of 192 and might be more reproducible (??), but it fails at runtime.

**Comment by valassi** [comment] 2022-04-14 09:20
Grrrrr... more importantly, CURAND_ORDERING_PSEUDO_DYNAMIC also fails at runtime. This "can be different on different GPUs. It is not guaranteed to: remain the same for all cuRAND releases, and be the same for all distributions. It is guaranteed to be deterministic." - deterministic is what I would like...

**Comment by valassi** [comment] 2022-04-14 09:23
Hm... on the other hand "It will always be the case that the ordering obtained with CURAND_ORDERING_PSEUDO_BEST is deterministic and is the same for each run of the program. " - this is probably why I chose it.

The problem however is that we seem to get different random numbers for host and device, and this is not really deterministic...

**Comment by valassi** [comment] 2022-04-14 10:41
I am running out of ideas.
https://docs.nvidia.com/cuda/curand/host-api-overview.html#host-api-example
"Generating random numbers on the device will result in the same sequence as generating them on the host CPU. "
To me, it seems like there is a bug in CUDA...

**Comment by valassi** [comment] 2022-04-14 11:02
OK I have added an ugly workaround: I destroy and recreate the generator at every seedGenerator call ie at every new iteration. The problem seems to happen only for the iterations after the first one, so internally the CUDA bug must be somewhere there, and I am now bypassing it. Ugly, and not performant, but who cares - I prefer reproducibility, an dthe only performance I care about is that of the ME, not that of curand...

```
./check.exe   -p 1 32 1              ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./gcheck.exe  -p 1 32 1              ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./check.exe  --bridge -p 1 32 1      ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
./gcheck.exe --bridge -p 1 32 1      ==> MeanMatrixElemValue         = ( 1.667198e+00 +- 3.998810e-01 )  GeV^0
------------------------------
./check.exe   -p 1 32 2              ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./gcheck.exe  -p 1 32 2              ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./check.exe  --bridge -p 1 32 2      ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
./gcheck.exe --bridge -p 1 32 2      ==> MeanMatrixElemValue         = ( 2.057781e+00 +- 4.150183e-01 )  GeV^0
------------------------------
./check.exe   -p 1 256 2             ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./gcheck.exe  -p 1 256 2             ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./check.exe  --bridge -p 1 256 2     ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
./gcheck.exe --bridge -p 1 256 2     ==> MeanMatrixElemValue         = ( 2.132806e+00 +- 1.649643e-01 )  GeV^0
------------------------------
./check.exe   -p 16 256 2            ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./gcheck.exe  -p 16 256 2            ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./check.exe  --bridge -p 16 256 2    ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
./gcheck.exe --bridge -p 16 256 2    ==> MeanMatrixElemValue         = ( 2.122875e+00 +- 3.953630e-02 )  GeV^0
------------------------------
./check.exe   -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe  -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./check.exe  --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
------------------------------
```

**Comment by valassi** [comment] 2022-04-14 11:03
I am preparing a PR for this.

**Comment by roiser** [comment] 2022-04-14 11:04
How much are we spending in curand?

**Comment by valassi** [comment] 2022-04-14 11:05
What I call a cuda bug is the following:
- I create a generator, seed it with seed1, then seed it with seed 2, I get a set of results
- I create a generator, seed it with seed 2, I get a different set of results from the case above
Maybe this is a feature, not a bug - but I want strict reproducibility

**Comment by valassi** [comment] 2022-04-14 11:08
> How much are we spending in curand?

I think not much - I mean, certainly much less than ME calculations (or even rambo I guess), especially for complex processes. So I would say the impact of this workaround is totally negligible.

I think I also have some tests which might measure this. But again, we are ONLY using curand in our standalone stuff now, while we are concentrating on MadEvent integration, where MadEvent also does the RANMAR random generation. So this is totally irrelevant for the final MadEvent+cudacpp product.

**Comment by valassi** [comment] 2022-04-14 11:24
Ok this is fixed by PR #430 that I am about to merge - closing this... thanks Stefan for reporting! Bizarre issue!

**Closed by valassi** 2022-04-14 11:24 UTC

**Comment by valassi** [comment] 2022-04-14 11:28
PS I confirm that the original issue is solved:
```
for args in "-p 32 32 1" "-p 32 32 2" "-p 32 256 2"; do
  for brd in "" "--bridge"; do
    for exe in "./check.exe " "./gcheck.exe"; do
      cmd="$exe $brd $args"
      printf "%-36s ==> " "$cmd"
      eval $cmd | grep MeanM
    done
  done
  echo "------------------------------"
done
./check.exe   -p 32 32 1             ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
./gcheck.exe  -p 32 32 1             ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
./check.exe  --bridge -p 32 32 1     ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
./gcheck.exe --bridge -p 32 32 1     ==> MeanMatrixElemValue         = ( 2.159376e+00 +- 1.218376e-01 )  GeV^0
------------------------------
./check.exe   -p 32 32 2             ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
./gcheck.exe  -p 32 32 2             ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
./check.exe  --bridge -p 32 32 2     ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
./gcheck.exe --bridge -p 32 32 2     ==> MeanMatrixElemValue         = ( 2.114776e+00 +- 8.028899e-02 )  GeV^0
------------------------------
./check.exe   -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe  -p 32 256 2            ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./check.exe  --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
./gcheck.exe --bridge -p 32 256 2    ==> MeanMatrixElemValue         = ( 2.106827e+00 +- 2.749649e-02 )  GeV^0
------------------------------
```

Also,

```
./gcheck.exe -v 32 32 2 | tail -8
Momenta:
   1  7.500000e+02  0.000000e+00  0.000000e+00  7.500000e+02
   2  7.500000e+02  0.000000e+00  0.000000e+00 -7.500000e+02
   3  7.500000e+02 -6.264599e+02 -4.169666e+01 -4.102552e+02
   4  7.500000e+02  6.264599e+02  4.169666e+01  4.102552e+02
-------------------------------------------------------------------------------
 Matrix element = 0.862187 GeV^0
-------------------------------------------------------------------------------

./gcheck.exe --bridge -v 32 32 2 | tail -8
Momenta:
   1  7.500000e+02  0.000000e+00  0.000000e+00  7.500000e+02
   2  7.500000e+02  0.000000e+00  0.000000e+00 -7.500000e+02
   3  7.500000e+02 -6.264599e+02 -4.169666e+01 -4.102552e+02
   4  7.500000e+02  6.264599e+02  4.169666e+01  4.102552e+02
-------------------------------------------------------------------------------
 Matrix element = 0.862187 GeV^0
-------------------------------------------------------------------------------
```

Stefan please let me know if you still see issues...

**Comment by roiser** [comment] 2022-04-14 11:54
Thanks @valassi I confirm its fixed now
