### ISSUE TITLE
Compilation Error in cudacpp_backend=cpp for CMS DY+nj and TT+nj (nvcc exists but not NVTX or curand)

### ISSUE THREAD

**Issue by choij1589** [madgraph5/madgraph4gpu#965] opened 2024-08-13 12:45 UTC
When attempting to compile the project using the ```cudacpp_backend = cpp``` configuration, encounter a compilation error with CMS DY+nj and TT+nj processes.

## Steps to reproduce
1. Used madgraph4gpu master branch (Aug 13., 2024)
2. proc_cards and run_cards are here: [DY0j_LO_5f_CPP](https://github.com/choij1589/genproductions/tree/mg4gpu/bin/MadGraph5_aMCatNLO/cards/13p6TeV/mg4gpu/DY0j_LO_5f_CPP)
3. Please modify $DEFAULT_PDF_SETS to 325300 and erase the line with $DEFAULT_PDF_MEMBERS: [run_card.dat](https://github.com/choij1589/genproductions/blob/mg4gpu/bin/MadGraph5_aMCatNLO/cards/13p6TeV/mg4gpu/DY0j_LO_5f_CPP/DY0j_LO_5f_CPP_run_card.dat#L34-L35)
4. launch event generation

## Environements
Using gcc-12 with CUDA 12.2, but also encountered same error in CUDA 11.8 

Compilation fails with the logs below:
[run_01_tag_1_debug.log](https://github.com/user-attachments/files/16599615/run_01_tag_1_debug.log)

**Comment by valassi** [comment] 2024-08-14 09:18
Hi Jin, thanks a lot for the details :-)

I think that the problem here is NOT related to the process DY or TT.

The problem is instead most likely related to your build environment. I managed to reproduce it by creating a dummy `nvcc` script and adding it to my path, but without a real cuda installation
```
echo "echo HALLO" > nvcc
chmod +x nvcc
\mv nvcc ~/bin
rehash
nvcc
  HALLO
```
and then
```
[avalassi@itgold91 gcc11/usr] /data/avalassi/GPU2024/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx> make -j -f cudacpp.mk
...
ccache g++ -o fcheck_cpp.exe ./fcheck_sa_fortran.o  ./fsampler_cpp.o -L../../lib -lmg5amc_common_cpp -Wl,-rpath='$ORIGIN/../../lib'  -lgfortran -L../../lib -lmg5amc_gg_ttx_cpp ./CommonRandomNumberKernel_cpp.o ./RamboSamplingKernels_cpp.o
In file included from timermap.h:17,
                 from check_sa.cc:26:
nvtx.h:22:10: fatal error: nvtx3/nvToolsExt.h: No such file or directory
   22 | #include "nvtx3/nvToolsExt.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [cudacpp.mk:725: check_sa_cpp.o] Error 1
make: *** Waiting for unfinished jobs....
CurandRandomNumberKernel.cc:14:10: fatal error: curand.h: No such file or directory
   14 | #include "curand.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [cudacpp.mk:725: CurandRandomNumberKernel_cpp.o] Error 1
[avalassi@itgold91 gcc11/usr] /data/avalassi/GPU2024/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx> 
```

Explanation:
- if nvcc is in the path, the cudacpp build dystem automatically assumes that NVTX and also CURAND exist... this is what I must change
- the fact that NVCC can be installed but not CURAND is something that @Saptaparna had already reported and I had already fixed in #785 (completing a previous patch by Stefan in #784), so this is kind of 'expected'
- I am much more surprised that you have an environment where nvcc exists but not NVTX... but I guess that may happen?

Workaround? 
- Already now, you can try to `export HASCURAND=hasNoCurand` (from PR 784 etc) and `export USE_NVTX=` and this should work
```
[avalassi@itgold91 gcc11/usr] /data/avalassi/GPU2024/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx> USE_NVTX= HASCURAND=hasNoCurand make -j -f cudacpp.mk
[all ok]
```

Anyway: I will try to add some more internal cross checks in the build system so that USE_NVTX and HASCURAND are disabled if nvcc exists but not NVTX or CURAND

**Comment by valassi** [comment] 2024-08-14 09:20
> Compilation fails with the logs below:
> [run_01_tag_1_debug.log](https://github.com/user-attachments/files/16599615/run_01_tag_1_debug.log)

PS The relevant bits from your log (thanks!) are
```
    BACKEND=cppavx2 (was cppauto)
    OMPFLAGS=
    FPTYPE='d'
    HELINL='0'
    HRDCOD='0'
    HASCURAND=hasCurand
    HASHIPRAND=hasNoHiprand
    Building in BUILDDIR=. for tag=avx2_d_inl0_hrd0_hasCurand_hasNoHiprand (USEBUILDDIR != 1)
    gfortran -I. -fPIC -c fcheck_sa.f -o fcheck_sa_fortran.o
    make -C ../../src  -f cudacpp_src.mk
    make[3]: Entering directory '/home/devuser/workspace/MG4GPU/Test_Aug_Week3/madgraph4gpu/MG5aMC/mg5amcnlo/DY0j_LO_5f_CPP/src'
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -DUSE_NVTX -I/cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_9/external/el8_amd64_gcc12/include/ -DMGONGPU_HAS_NO_HIPRAND -c check_sa.cc -o check_sa_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c CPPProcess.cc -o CPPProcess_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c MatrixElementKernels.cc -o MatrixElementKernels_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c BridgeKernels.cc -o BridgeKernels_cpp.o
    g++  -I. -I../../src -O3 -std=c++17 -Wall -Wshadow -Wextra -march=haswell -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -fno-fast-math -c CrossSectionKernels.cc -o CrossSectionKernels_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c fbridge.cc -o fbridge_cpp.o
    g++  -I. -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c Parameters_sm_no_b_mass.cc -o Parameters_sm_no_b_mass_cpp.o
    g++  -I. -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c read_slha.cc -o read_slha_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c CommonRandomNumberKernel.cc -o CommonRandomNumberKernel_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c RamboSamplingKernels.cc -o RamboSamplingKernels_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -DMGONGPU_HAS_NO_HIPRAND -I/cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_9/external/el8_amd64_gcc12/include/ -c CurandRandomNumberKernel.cc -o CurandRandomNumberKernel_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -DMGONGPU_HAS_NO_HIPRAND -c HiprandRandomNumberKernel.cc -o HiprandRandomNumberKernel_cpp.o
    g++  -I. -I../../src -O3  -std=c++17 -Wall -Wshadow -Wextra -ffast-math   -march=haswell  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -fPIC -c fsampler.cc -o fsampler_cpp.o
    In file included from timermap.h:17,
                     from check_sa.cc:26:
    nvtx.h:22:10: fatal error: nvtx3/nvToolsExt.h: No such file or directory
       22 | #include "nvtx3/nvToolsExt.h"
          |          ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [cudacpp.mk:726: check_sa_cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CurandRandomNumberKernel.cc:14:10: fatal error: curand.h: No such file or directory
       14 | #include "curand.h"
          |          ^~~~~~~~~~
    compilation terminated.
```

**Comment by choij1589** [comment] 2024-08-17 05:18
Many thanks @valassi! I have tested with ```export HACURAND=hasNoCurand``` and ```export USE_NVTX=``` and the compilation was successful. I would investigate why nvcc in CMSSW has no such libraries (or might need additional setup?), but I think we can close this issue.

**Comment by valassi** [comment] 2024-08-17 07:58
Hi @choij1589 thanks to you I am happy this works!

I had in any case also created PR #966 which should normally fix the issue out of the box. That is, you should be able to just build without setting yourself HASCURAND or USE_NVTX (and I actually removed th eoption to change USE_NVTX). Maybe you could also try that please?

As for CMSSW libraries, I guess it is more a node-specific issues than CMSSW, but I may be wrong. Let me know if you need help. But optherwise I think it's not really important to understand why that happens now, what is important is to know the spread of environments we may need to support (i.e, if you find yet another different configuration, please report it!)

Thanks Andrea

**Comment by choij1589** [comment] 2024-08-19 04:12
Hi @valassi, I have tested with PR [#966](https://github.com/madgraph5/madgraph4gpu/pull/966), without explicitly setting HASCURAND or USE_NVTX, and the compilation and final output gridpack were successful!

For CMSSW libraries, I'm not sure if you are worrying about the installed CUDA in each node environment, but nvcc and other header files are installed within each gcc & cuda directories within CVFMS
(e.g. nvcc installed in ```/cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_9/external/el8_amd64_gcc12/bin/nvcc``` 
$\to$ ```/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/bin/nvcc```).
So once the version is fixed, as I'm using docker image for OS configuration, it is okay throughout the node environment.

Many Thanks!
Jin

**Comment by valassi** [comment] 2024-08-19 21:11
> Hi @valassi, I have tested with PR [#966](https://github.com/madgraph5/madgraph4gpu/pull/966), without explicitly setting HASCURAND or USE_NVTX, and the compilation and final output gridpack were successful!

Thanks @choij1589 ! 

@oliviermattelaer can you approve #966? It should be rather non controversial, and standalone. Thanks



> For CMSSW libraries, I'm not sure if you are worrying about the installed CUDA in each node environment, but nvcc and other header files are installed within each gcc & cuda directories within CVFMS
> (e.g. nvcc installed in `/cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_9/external/el8_amd64_gcc12/bin/nvcc`
> → `/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/bin/nvcc`).
> So once the version is fixed, as I'm using docker image for OS configuration, it is okay throughout the node environment.

Thanks Jin, I will keep this in mind! For the moment I am not trying to do anything more precise about the CMS environment, but you never know what else may appear...

Cheers
Andrea

PS I will close this when #966 is merged

**Closed** 2024-08-21 09:05 UTC
