### ISSUE TITLE
Implement parallel loops in C++ version of CUDA code

### ISSUE THREAD

**Issue by hageboeck** [madgraph5/madgraph4gpu#82] opened 2020-12-03 10:47 UTC
Since events have no data dependencies, multi-threading across events should be possible. Investigate parallel for loops, e.g. `#pragma omp parallel for`.

**Comment by lfield** [comment] 2020-12-03 10:54
@hageboeck I initially looked at doing exactly that and it would be one approach. For simple events this makes sense. This is more of an objective question. Where is the concurrency and what are we targeting.

**Comment by hageboeck** [comment] 2020-12-03 11:09
It's to get away from this:
A: We compared the GPU with a single thread on a CPU. It's x times faster.
B: But that's not fair. You should compare to multi-threading on a modern CPU.

The objective is to grab the low-hanging fruit by just doing that where appropriate:
```diff
  #ifndef __CUDACC__
    //** START LOOP ON IEVT **
+  #pragma omp parallel for
    for (int ievt = 0; ievt < nevt; ++ ievt)
  #endif
    {
  #ifdef __CUDACC__
      const int idim = blockDim.x * blockIdx.x + threadIdx.x;  // event# == threadid (previously was: tid)
      const int ievt = idim; 
      // printf( "sigmakin: ievt %d\n", ievt );
  #endif
```

**Comment by valassi** [comment] 2020-12-03 11:14
Hi Stephan, thanks, very good! 

As I was proposing last Monday, CPU multi-threading with each thread running a different sets of events is what we should aim for. In principle there should be no thread safety issue (or if there is, we should fix it). We should try to fill up a CPU when we compare GPU to CPU, and a single MT application seems better than different instances of the application.

What I was initially thinking of was simple pthread threading (e.g. c++11 threads as you suggested). 

But your later suggestion for #pragma omp parallel for seems even better to me! First it would be less intrusive on the code, second the level of multithreading can be set by using OMP_NUM_THREADS (otherwise we would need to pass yet another command line argument).

My point in raising the issue on Monday was also that this would allow us to compare to the abstraction layers like Alpaka et al, which on the CPU probably do exactly this. Doing the MT directly in our c++ would be faster and probably easier, especially if we only need a single line of OpenMP.

The line you added was exactky where I was going to suggest it ;-)
https://github.com/madgraph5/madgraph4gpu/blob/9ebd056d2ff792bd027088526f5f1a870d505826/epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc#L706

Very good, make a PR and let's see... :-)
Andrea

**Comment by valassi** [comment] 2020-12-03 11:29
PS One immediate test to do once this is done is a full scalability test, increasing the number of OpenMP threads and plotting throughput with respect to the number of OpenMP threads. This should go to the number of cores, then 2x the number of cores (hyperthreading) and maybe beyond to 4x, just as a cross check. Probably linear from 0 until #cores, then some increase till 2x, then maybe flat.

This reminds me some discussion we had with @lfield in July, when he had tested hipsycl and he had found a decrease from 28.5 seconds to 3.5 seconds for 1M events. This was on a machine nominally with 4 threads, but I was suggesting that the speedup was probably from hyperthreading, so almost a factor 8 (x4 physical cores, and almost x2 additional from hyperthreading). It is essential that we understand this sort of details.

The advantage of openmp is that we can get all the benefits with one single line, without installing hipsycl, or alpaka etc. We still need to install/locate openmp, but that is also an internal dependency of these layers, so we get fewere, simpler dependencies and simpler code. Give it a try Stephan!

Thanks

**Comment by hageboeck** [comment] 2020-12-03 12:00
We might actually run into problems, because our VMs don't allow for test with/without hyperthreading, but I can get a real machine to test on. :-)

About the dependency:
OMP is a very light dependency, because gcc supports it natively since gcc v4. You just need to find link against libgomp, but that's easy to install or already present on most systems.

Let me get the paper stuff done, and I'll test it.

**Comment by lfield** [comment] 2020-12-03 12:17
I already tested this back in April/May with OpenMP. This issue I found was that the code is not thread safe. The for loop was after the initial setup and the CPProcess object was being shared. There is also the issue of the race condition in the random number generator etc. etc. The code is quite different now but it may still take some work to get this working. Decorating for loops with pragma statements is an elegant and simple approach but only works if the code is ready for it.  
Most of the frameworks, SYCL included, in any case use OpenMP under the hood to run the code on the CPU.

**Comment by valassi** [comment] 2020-12-03 14:05
Thanks both!

@hageboeck , no problem to find a test machine, we have the pmpe cluster which are physical machine.

@lfield, good point, CPPProcess at the time was probably not thread safe. This is something that we (especially @oliviermattelaer) should keep in mind when designing a cleaner version of the interface. I am reasonably sure that now it should be thread safe, or at least can be fixable easily. 

Note that the code we indicated previously in https://github.com/madgraph5/madgraph4gpu/blob/9ebd056d2ff792bd027088526f5f1a870d505826/epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc#L706,
```
  #ifndef __CUDACC__
    //** START LOOP ON IEVT **
+   #pragma omp parallel for
    for (int ievt = 0; ievt < nevt; ++ ievt)
  #endif
    {
  #ifdef __CUDACC__
      const int idim = blockDim.x * blockIdx.x + threadIdx.x;  // event# == threadid (previously was: tid)
      const int ievt = idim; 
      // printf( "sigmakin: ievt %d\n", ievt );
  #endif
```
is the loop which is already executed by multiple threads on the GPU. In the GPU, each thread is assigned one ievt. On the CPU, we are now looping in a single main thread over all ievt's, but we could paralleize it on separate threads each doing a bunch of ievts. If it is "thread-safe" on the GPU, it should be thread safe on the CPU too out of the box.

Note that eventually I would move the "omp parallel for" from the current loop on the event index ievt to a future loop on an "event page" index ipagV
https://github.com/valassi/madgraph4gpu/blob/4744088cecdb91493a7854c6d1e93a322661938f/epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc#L566
This is discussed in #71. The idea is to achieve also SIMD vectorization. So, essentially, the parallization would be:
- subdivide the nevt events into npagV pages with neppV events each
  - this is both on the CPU and the GPU, though the values of neppV may be different on CPU and GPU as detailed below
- structure all relevant memory arrays (momenta, in particular) as Arrays Of Structure Of Arrays where neppV is the last dimension, [npagV][... structure ...][neppV]
- on the CPU:
  - loop over the npagV pages, using OpenMP to split that into several threads
  - use SIMD vectorization if possible to help in the loop over the neppV events in each page (the value of neppV on the CPU should be tuned for the SIMD capabilities of the specific CPU)
- on the GPU:
  - let a separate GPU thread process each of the nevt different events ievt
  - use the AOSOA structure to allow optimal (coalesced) data access (the value of neppV on the GPU is already tuned for this, essentially it is the lowest value allowing coalesced retrieval of a 32-byte cacheline)

**Comment by lfield** [comment] 2020-12-03 14:41
@valassi it is easy enough to try. After adding the pragma statement just add `-fopenmp ` as a compile option and use OMP_NUM_THREADS to compare the single and multi-threaded performance.

**Comment by valassi** [comment] 2020-12-03 16:15
Thanks @lfield, it was indeed easy!

Just one line change in a .cc file, and one line change in a Makefile!
https://github.com/madgraph5/madgraph4gpu/pull/84/commits/6a1649ab852672b6ad24365901ad3bc5f9e325bb

However, there is a conflict caused by an underlying issue, runTest.exe no longer builds (#83).
A real fix is needed, separating two executables for cuda and c++.
But I have added a temporary workaround for that,
https://github.com/madgraph5/madgraph4gpu/pull/84/commits/6572f98cc811a6a4164ee795ac60354e675206d0

As shown in that commit, there is a nice immediate effect, even on a VM (with `nproc --all`=4):
```
export OMP_NUM_THREADS=1; ./check.exe -p 16384 32 1
EvtsPerSec[MatrixElems] (3)= ( 3.841438e+05                 )  sec^-1

export OMP_NUM_THREADS=1; ./check.exe -p 16384 32 1
EvtsPerSec[MatrixElems] (3)= ( 1.515065e+06                 )  sec^-1

export OMP_NUM_THREADS=8; ./check.exe -p 16384 32 1
EvtsPerSec[MatrixElems] (3)= ( 1.516047e+06                 )  sec^-1
```

Definitely an easy and effective improvement!
Thanks @hageboeck and @lfield!
Andrea

**Comment by valassi** [comment] 2020-12-03 16:17
PS to be understood: nproc is 1, only nproc --all is 4 on the VM.
Maybe the default shell uses by default 1 core only?
The VM in any case is built in openstack with 4 cores, so we do "own" all 4 cores, we are not stelaing them away from the hypervisor.

**Comment by valassi** [comment] 2020-12-03 16:51
> 
> 
> We might actually run into problems, because our VMs don't allow for test with/without hyperthreading, but I can get a real machine to test on. :-)
> 
> About the dependency:
> OMP is a very light dependency, because gcc supports it natively since gcc v4. You just need to find/link against libgomp, but that's easy to install or already present on most systems.
> 
> Let me get the paper stuff done, and I'll test it.

About this issue, actually I did not have to add any libgomp to the link, only the -fopenmp suggested by Laurence
```
/cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/bin/g++ check.o -o check.exe CPPProcess.o  -O3 -std=c++11 -I. -I../../src -I../../../../../tools/ -DUSE_NVTX -Wall -Wshadow -fopenmp  -ldl -pthread -L../../lib -lmodel_sm -L/usr/local/cuda-11.1/lib64/ -lcuda -lcurand
```

This might be because I am using a gcc provided by the SFT LCG stack, so it contains already the library. But the linker adds it automatically if it is not on the command line:
```
ldd ./check.exe 
        linux-vdso.so.1 (0x00007fff85be7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0012cee000)
        libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f00116c4000)
        libcurand.so.10 => /usr/local/cuda-10.2/lib64/libcurand.so.10 (0x00007f000d621000)
        libstdc++.so.6 => /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/lib64/libstdc++.so.6 (0x00007f000d298000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f000cf16000)
        libgomp.so.1 => /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/lib64/libgomp.so.1 (0x00007f000cce7000)
        libgcc_s.so.1 => /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-centos7/lib64/libgcc_s.so.1 (0x00007f000cacf000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f000c8af000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f000c4ed000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0012ef2000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f000c2e4000)
```

**Comment by valassi** [comment] 2020-12-03 17:02
PS Same is true with native gcc 8.3.1 from our centos8 nodes
```
g++ check.o -o check.exe CPPProcess.o  -O3 -std=c++11 -I. -I../../src -I../../../../../tools/ -DUSE_NVTX -Wall -Wshadow -fopenmp  -ldl -pthread -L../../lib -lmodel_sm -L/usr/local/cuda-11.1/lib64/ -lcuda -lcurand

g++ --version
g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd ./check.exe 
        linux-vdso.so.1 (0x00007ffcebfe8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f53ae72c000)
        libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f53ad102000)
        libcurand.so.10 => /usr/local/cuda-10.2/lib64/libcurand.so.10 (0x00007f53a905f000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f53a8cca000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f53a8948000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f53a8710000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f53a84f8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f53a82d8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f53a7f16000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f53ae930000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f53a7d0d000)

rpm -qf /lib64/libgomp.so.1
libgomp-8.3.1-5.el8.0.2.x86_64
```

Note that if I try `yum erase libgomp`, then it asks me if it can erase 262 packages, including gcc but much much more. So, in short, at least as of gcc83, libgomp is part of the system.

**Comment by lfield** [comment] 2020-12-03 19:50
Yes, OpenMP is really nice for quickly doing things. It has been supported by GCC since v4.9. From GGC 7 you can offload to  Nvidia PTX targets.

```
-fopenmp
           Enable handling of OpenMP directives "#pragma omp" in C/C++ and
           "!$omp" in Fortran.  When -fopenmp is specified, the compiler
           generates parallel code according to the OpenMP Application Program
           Interface v4.5 <https://www.openmp.org>.  This option implies
           -pthread, and thus is only supported on targets that have support
           for -pthread. -fopenmp implies -fopenmp-simd.`
```

**Comment by valassi** [comment] 2020-12-09 22:09
This is done. The PR is merged.

En passant: in the klas branch for vectorization, I had to add some private variables in the omp parallel for. Performance was badly degrading otherwise. See https://github.com/madgraph5/madgraph4gpu/pull/72/commits/5e90bc80cb9a010a8b56e4b0d608704b1c0b4be9

Closing.

**Closed by valassi** 2020-12-09 22:09 UTC
Labels: enhancement
