### ISSUE TITLE
Overflow error in gg_ttgg example

### ISSUE THREAD

**Issue by tjburch** [madgraph5/madgraph4gpu#79] opened 2020-12-01 18:53 UTC
In my conversion to SYCL, I noticed I was getting some NAN values for components (V2[5] specifically) in the `VVV1P0_1` function in CPPProcess. I tried to mirror the behavior in CUDA, and found what appears to be an overflow error, tracing back to the `vxxxxx` function.

Looking at 293 here - https://github.com/madgraph5/madgraph4gpu/blob/master/epoch1/cuda/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/CPPProcess.cu#L293

If I print the components of this square root function:

```
========= sqrt Components:  p[1]=-958189386
========= sqrt Components:  p[1]*p[1]=-1679619596
========= sqrt Components:  p[2]=-1982430220
========= sqrt Components:  p[2]*p[2]=-2100755297
========= sqrt Components:  p[3]=-2045069892
========= sqrt Components:  p[3]*p[3]=-1131260949
========= sqrt Components:  vmass=0
========= sqrt Components:  vmass*vmass=0
========= sqrt Final Argument:  arg=-1689285092
```

There's already overflows in the individual components, and then that propagates to the square root function, which gets an unexpected negative value.

(@oliviermattelaer and @roiser, labeled you as assignees just to see if there were ideas here)

**Comment by lfield** [comment] 2020-12-01 19:31
@tjburch This sounds like the issue that I discovered when I did the first SYCL port in July. The [ranmar function](https://github.com/madgraph5/madgraph4gpu/blob/master/epoch1/cuda/gg_ttgg/src/rambo.cc#L9) in rambo.cc is not thread safe. The variables jranmr and iranmr are shared by the threads and the equal to zero check for those variables can fail due to a race condition where the value becomes less than zero. The simple fix is to change the equals to less than and using the common random numbers approach will also work until we find a general solution for random number generation.

**Comment by oliviermattelaer** [comment] 2020-12-01 20:10
@lfield good catch.

**Comment by tjburch** [comment] 2020-12-01 21:33
Thanks @lfield, good to know.

>using the common random numbers approach

I'm not familiar, what do I need to implement this?

**Comment by hageboeck** [comment] 2020-12-02 08:16
For common random numbers, you can include this
https://github.com/madgraph5/madgraph4gpu/blob/master/tools/CommonRandomNumbers.h,
and call one of the functions.

The functions should be thread safe in the sense that you can call them as many times as you want, but you have to say in advance how many numbers you need per batch, and you have to set up the seed manually if you don't generate all batches in advance.

**Comment by valassi** [comment] 2020-12-03 18:12
Nice finds. Just a comment, I assume this is only an issue with old code, like epoch0? I mean, ranmar is long gone.

For the mainstream epoch1 eemumu (and all epoch2 I assume) we will have curand on GPU and also on CPU.

Only for some asbtraction layers it is necessary to use the common c++11 random numbers from Stephan.

I am just trying to understand if we should expect thread safety issues for mainstream cuda development (or even for c++ OMP), but I assume we should not, because ranmar is long gone. Am I getting this wrong?

**Comment by tjburch** [comment] 2020-12-07 04:18
>Nice finds. Just a comment, I assume this is only an issue with old code, like epoch0? I mean, ranmar is long gone.

ranmar persists in the gg_ttgg example for epoch1. You're right it's not in the epoch1 for ee->mumu. 

>I am just trying to understand if we should expect thread safety issues for mainstream cuda development (or even for c++ OMP), but I assume we should not, because ranmar is long gone. Am I getting this wrong?

I have not encountered this problem when running the ee->mumu example and the issues seem localized to ranmar, so I think we should not expect thread-safety issues.

**Comment by valassi** [comment] 2021-10-21 10:54
Hi, with the latest work on code generation in epochX (issue #244), all processes now use the same code - without ranmar.

I assume that this makes this issue #79 obsolete? Maybe @lfield can you please comment if sycl still uses ranmar (or more precisely if it still has this overflow error)? Otherwise I would close this. Thanks :-)

**Comment by valassi** [comment] 2021-12-13 13:14
Closing this issue as I think it's confirmed as obsolete - thanks again @tjburch !

**Closed by valassi** 2021-12-13 13:14 UTC
